eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8765
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
#        - id: test1
#          predicates:
#            - Path=/main/test
#            - Method=GET
#          uri: lb://eu-client
#        - id: test2
#          filters:
#            - StripPrefix=1
#          predicates:
#            - Path=/u2/new/name
#            - Method=GET
#          uri: lb://eu-client-2
        - id: test3
          filters:
            - StripPrefix=1
            - PrefixPath=/eu1
          predicates:
            - Path=/test/**
            - Method=GET
          uri: lb://eu-client
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'