server:
  port: 8888
spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: file://C:/temp/java/ms-demo/config-store
#          uri: https://github.com/kalenikov/ms-demo-config.git
#          clone-on-start: true
#          basedir: file://c:/temp/java/ms-demo-temp
#          username: skalenikov
#          password: 123
#          default-label: main
